version: '3.8'

services:
  ctabot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOTENV: DOCKER
      BOT_TOKEN: ${BOT_TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: always
    depends_on:
      db:
        condition: service_healthy    
        

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/ # Mount the init folder for scripts
    healthcheck:
      test: ["CMD", "pg_isready", "-U", $DATABASE_USER, "-d", $DATABASE_NAME]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: always

volumes:
  postgres_data:

